/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class darray {
  public static void myMethod(SWIGTYPE_p_double values, int size) {
    darrayJNI.myMethod(SWIGTYPE_p_double.getCPtr(values), size);
  }

  public static SWIGTYPE_p_double new_double_array(int nelements) {
    long cPtr = darrayJNI.new_double_array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_double_array(SWIGTYPE_p_double ary) {
    darrayJNI.delete_double_array(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double double_array_getitem(SWIGTYPE_p_double ary, int index) {
    return darrayJNI.double_array_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void double_array_setitem(SWIGTYPE_p_double ary, int index, double value) {
    darrayJNI.double_array_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

}
