/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DVec extends java.util.AbstractList<Double> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        innerJNI.delete_DVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public DVec(double[] initialElements) {
    this();
    reserve(initialElements.length);

    for (double element : initialElements) {
      add(element);
    }
  }

  public DVec(Iterable<Double> initialElements) {
    this();
    for (double element : initialElements) {
      add(element);
    }
  }

  public Double get(int index) {
    return doGet(index);
  }

  public Double set(int index, Double e) {
    return doSet(index, e);
  }

  public boolean add(Double e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Double e) {
    modCount++;
    doAdd(index, e);
  }

  public Double remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public DVec() {
    this(innerJNI.new_DVec__SWIG_0(), true);
  }

  public DVec(DVec other) {
    this(innerJNI.new_DVec__SWIG_1(DVec.getCPtr(other), other), true);
  }

  public long capacity() {
    return innerJNI.DVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    innerJNI.DVec_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return innerJNI.DVec_isEmpty(swigCPtr, this);
  }

  public void clear() {
    innerJNI.DVec_clear(swigCPtr, this);
  }

  public DVec(int count, double value) {
    this(innerJNI.new_DVec__SWIG_2(count, value), true);
  }

  private int doSize() {
    return innerJNI.DVec_doSize(swigCPtr, this);
  }

  private void doAdd(double x) {
    innerJNI.DVec_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, double x) {
    innerJNI.DVec_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private double doRemove(int index) {
    return innerJNI.DVec_doRemove(swigCPtr, this, index);
  }

  private double doGet(int index) {
    return innerJNI.DVec_doGet(swigCPtr, this, index);
  }

  private double doSet(int index, double val) {
    return innerJNI.DVec_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    innerJNI.DVec_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
