/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class inner {
  public static double inner_product(DVec arg0, DVec arg1) {
    return innerJNI.inner_product(DVec.getCPtr(arg0), arg0, DVec.getCPtr(arg1), arg1);
  }

}
