/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class innerJNI {
  public final static native double inner_product(long jarg1, DVec jarg1_, long jarg2, DVec jarg2_);
  public final static native long new_DVec__SWIG_0();
  public final static native long new_DVec__SWIG_1(long jarg1, DVec jarg1_);
  public final static native long DVec_capacity(long jarg1, DVec jarg1_);
  public final static native void DVec_reserve(long jarg1, DVec jarg1_, long jarg2);
  public final static native boolean DVec_isEmpty(long jarg1, DVec jarg1_);
  public final static native void DVec_clear(long jarg1, DVec jarg1_);
  public final static native long new_DVec__SWIG_2(int jarg1, double jarg2);
  public final static native int DVec_doSize(long jarg1, DVec jarg1_);
  public final static native void DVec_doAdd__SWIG_0(long jarg1, DVec jarg1_, double jarg2);
  public final static native void DVec_doAdd__SWIG_1(long jarg1, DVec jarg1_, int jarg2, double jarg3);
  public final static native double DVec_doRemove(long jarg1, DVec jarg1_, int jarg2);
  public final static native double DVec_doGet(long jarg1, DVec jarg1_, int jarg2);
  public final static native double DVec_doSet(long jarg1, DVec jarg1_, int jarg2, double jarg3);
  public final static native void DVec_doRemoveRange(long jarg1, DVec jarg1_, int jarg2, int jarg3);
  public final static native void delete_DVec(long jarg1);
}
