/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1,
  SWIG_JavaIOException,
  SWIG_JavaRuntimeException,
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError,
  SWIG_JavaIllegalStateException,
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { SWIG_JavaIllegalStateException, "java/lang/IllegalStateException" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "example.h"


extern int              ivar;
extern short            svar;
extern long             lvar;
extern unsigned int     uivar;
extern unsigned short   usvar;
extern unsigned long    ulvar;
extern signed char      scvar;
extern unsigned char    ucvar;
extern char             cvar;
extern float            fvar;
extern double           dvar;
extern char            *strvar;
extern const char       cstrvar[];
extern int             *iptrvar;
extern char             name[256];

extern Point           *ptptr;
extern Point            pt;


extern int  status;
extern char path[256];


extern void  print_vars();
extern int  *new_int(int value);
extern Point *new_Point(int x, int y);
extern char  *Point_print(Point *p);
extern void  pt_print();


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_exampleJNI_ivar_1set(JNIEnv *jenv, jclass jcls, jint jarg1) {
  int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  ivar = arg1;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_ivar_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)ivar;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_svar_1set(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  short arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (short)jarg1; 
  svar = arg1;
}


SWIGEXPORT jshort JNICALL Java_exampleJNI_svar_1get(JNIEnv *jenv, jclass jcls) {
  jshort jresult = 0 ;
  short result;
  
  (void)jenv;
  (void)jcls;
  result = (short)svar;
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_lvar_1set(JNIEnv *jenv, jclass jcls, jint jarg1) {
  long arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (long)jarg1; 
  lvar = arg1;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_lvar_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)lvar;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_uivar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  unsigned int arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned int)jarg1; 
  uivar = arg1;
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_uivar_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  result = (unsigned int)uivar;
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_usvar_1set(JNIEnv *jenv, jclass jcls, jint jarg1) {
  unsigned short arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned short)jarg1; 
  usvar = arg1;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_usvar_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  unsigned short result;
  
  (void)jenv;
  (void)jcls;
  result = (unsigned short)usvar;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_ulvar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  unsigned long arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned long)jarg1; 
  ulvar = arg1;
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_ulvar_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  unsigned long result;
  
  (void)jenv;
  (void)jcls;
  result = (unsigned long)ulvar;
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_scvar_1set(JNIEnv *jenv, jclass jcls, jbyte jarg1) {
  signed char arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (signed char)jarg1; 
  scvar = arg1;
}


SWIGEXPORT jbyte JNICALL Java_exampleJNI_scvar_1get(JNIEnv *jenv, jclass jcls) {
  jbyte jresult = 0 ;
  signed char result;
  
  (void)jenv;
  (void)jcls;
  result = (signed char)scvar;
  jresult = (jbyte)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_ucvar_1set(JNIEnv *jenv, jclass jcls, jshort jarg1) {
  unsigned char arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (unsigned char)jarg1; 
  ucvar = arg1;
}


SWIGEXPORT jshort JNICALL Java_exampleJNI_ucvar_1get(JNIEnv *jenv, jclass jcls) {
  jshort jresult = 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  result = (unsigned char)ucvar;
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_cvar_1set(JNIEnv *jenv, jclass jcls, jchar jarg1) {
  char arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (char)jarg1; 
  cvar = arg1;
}


SWIGEXPORT jchar JNICALL Java_exampleJNI_cvar_1get(JNIEnv *jenv, jclass jcls) {
  jchar jresult = 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  result = (char)cvar;
  jresult = (jchar)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_fvar_1set(JNIEnv *jenv, jclass jcls, jfloat jarg1) {
  float arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (float)jarg1; 
  fvar = arg1;
}


SWIGEXPORT jfloat JNICALL Java_exampleJNI_fvar_1get(JNIEnv *jenv, jclass jcls) {
  jfloat jresult = 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  result = (float)fvar;
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_dvar_1set(JNIEnv *jenv, jclass jcls, jdouble jarg1) {
  double arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (double)jarg1; 
  dvar = arg1;
}


SWIGEXPORT jdouble JNICALL Java_exampleJNI_dvar_1get(JNIEnv *jenv, jclass jcls) {
  jdouble jresult = 0 ;
  double result;
  
  (void)jenv;
  (void)jcls;
  result = (double)dvar;
  jresult = (jdouble)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_strvar_1set(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  {
    free(strvar);
    if (arg1) {
      strvar = (char *) malloc(strlen((const char *)arg1)+1);
      strcpy((char *)strvar, (const char *)arg1);
    } else {
      strvar = 0;
    }
  }
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jstring JNICALL Java_exampleJNI_strvar_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)strvar;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_exampleJNI_cstrvar_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)(char *)cstrvar;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_iptrvar_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  int *arg1 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(int **)&jarg1; 
  iptrvar = arg1;
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_iptrvar_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (int *)iptrvar;
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_name_1set(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  {
    if(arg1) {
      strncpy((char*)name, (const char *)arg1, 256-1);
      name[256-1] = 0;
    } else {
      name[0] = 0;
    }
  }
  
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jstring JNICALL Java_exampleJNI_name_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)(char *)name;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_ptptr_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Point *arg1 = (Point *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Point **)&jarg1; 
  ptptr = arg1;
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_ptptr_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Point *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Point *)ptptr;
  *(Point **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_pt_1set(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Point arg1 ;
  Point *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(Point **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null Point");
    return ;
  }
  arg1 = *argp1; 
  pt = arg1;
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_pt_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Point result;
  
  (void)jenv;
  (void)jcls;
  result = pt;
  {
    Point * resultptr = (Point *) malloc(sizeof(Point));
    memmove(resultptr, &result, sizeof(Point));
    *(Point **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_exampleJNI_status_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)status;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_exampleJNI_path_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)(char *)path;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_print_1vars(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  print_vars();
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_new_1int(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  int *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (int *)new_int(arg1);
  *(int **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_exampleJNI_new_1Point(JNIEnv *jenv, jclass jcls, jint jarg1, jint jarg2) {
  jlong jresult = 0 ;
  int arg1 ;
  int arg2 ;
  Point *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  arg2 = (int)jarg2; 
  result = (Point *)new_Point(arg1,arg2);
  *(Point **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_exampleJNI_Point_1print(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  Point *arg1 = (Point *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Point **)&jarg1; 
  result = (char *)Point_print(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_exampleJNI_pt_1print(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  pt_print();
}


#ifdef __cplusplus
}
#endif

