/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native void ivar_set(int jarg1);
  public final static native int ivar_get();
  public final static native void svar_set(short jarg1);
  public final static native short svar_get();
  public final static native void lvar_set(int jarg1);
  public final static native int lvar_get();
  public final static native void uivar_set(long jarg1);
  public final static native long uivar_get();
  public final static native void usvar_set(int jarg1);
  public final static native int usvar_get();
  public final static native void ulvar_set(long jarg1);
  public final static native long ulvar_get();
  public final static native void scvar_set(byte jarg1);
  public final static native byte scvar_get();
  public final static native void ucvar_set(short jarg1);
  public final static native short ucvar_get();
  public final static native void cvar_set(char jarg1);
  public final static native char cvar_get();
  public final static native void fvar_set(float jarg1);
  public final static native float fvar_get();
  public final static native void dvar_set(double jarg1);
  public final static native double dvar_get();
  public final static native void strvar_set(String jarg1);
  public final static native String strvar_get();
  public final static native String cstrvar_get();
  public final static native void iptrvar_set(long jarg1);
  public final static native long iptrvar_get();
  public final static native void name_set(String jarg1);
  public final static native String name_get();
  public final static native void ptptr_set(long jarg1);
  public final static native long ptptr_get();
  public final static native void pt_set(long jarg1);
  public final static native long pt_get();
  public final static native int status_get();
  public final static native String path_get();
  public final static native void print_vars();
  public final static native long new_int(int jarg1);
  public final static native long new_Point(int jarg1, int jarg2);
  public final static native String Point_print(long jarg1);
  public final static native void pt_print();
}
