/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static void setIvar(int value) {
    exampleJNI.ivar_set(value);
  }

  public static int getIvar() {
    return exampleJNI.ivar_get();
  }

  public static void setSvar(short value) {
    exampleJNI.svar_set(value);
  }

  public static short getSvar() {
    return exampleJNI.svar_get();
  }

  public static void setLvar(int value) {
    exampleJNI.lvar_set(value);
  }

  public static int getLvar() {
    return exampleJNI.lvar_get();
  }

  public static void setUivar(long value) {
    exampleJNI.uivar_set(value);
  }

  public static long getUivar() {
    return exampleJNI.uivar_get();
  }

  public static void setUsvar(int value) {
    exampleJNI.usvar_set(value);
  }

  public static int getUsvar() {
    return exampleJNI.usvar_get();
  }

  public static void setUlvar(long value) {
    exampleJNI.ulvar_set(value);
  }

  public static long getUlvar() {
    return exampleJNI.ulvar_get();
  }

  public static void setScvar(byte value) {
    exampleJNI.scvar_set(value);
  }

  public static byte getScvar() {
    return exampleJNI.scvar_get();
  }

  public static void setUcvar(short value) {
    exampleJNI.ucvar_set(value);
  }

  public static short getUcvar() {
    return exampleJNI.ucvar_get();
  }

  public static void setCvar(char value) {
    exampleJNI.cvar_set(value);
  }

  public static char getCvar() {
    return exampleJNI.cvar_get();
  }

  public static void setFvar(float value) {
    exampleJNI.fvar_set(value);
  }

  public static float getFvar() {
    return exampleJNI.fvar_get();
  }

  public static void setDvar(double value) {
    exampleJNI.dvar_set(value);
  }

  public static double getDvar() {
    return exampleJNI.dvar_get();
  }

  public static void setStrvar(String value) {
    exampleJNI.strvar_set(value);
  }

  public static String getStrvar() {
    return exampleJNI.strvar_get();
  }

  public static String getCstrvar() {
    return exampleJNI.cstrvar_get();
  }

  public static void setIptrvar(SWIGTYPE_p_int value) {
    exampleJNI.iptrvar_set(SWIGTYPE_p_int.getCPtr(value));
  }

  public static SWIGTYPE_p_int getIptrvar() {
    long cPtr = exampleJNI.iptrvar_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void setName(String value) {
    exampleJNI.name_set(value);
  }

  public static String getName() {
    return exampleJNI.name_get();
  }

  public static void setPtptr(SWIGTYPE_p_Point value) {
    exampleJNI.ptptr_set(SWIGTYPE_p_Point.getCPtr(value));
  }

  public static SWIGTYPE_p_Point getPtptr() {
    long cPtr = exampleJNI.ptptr_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Point(cPtr, false);
  }

  public static void setPt(SWIGTYPE_p_Point value) {
    exampleJNI.pt_set(SWIGTYPE_p_Point.getCPtr(value));
  }

  public static SWIGTYPE_p_Point getPt() {
    return new SWIGTYPE_p_Point(exampleJNI.pt_get(), true);
  }

  public static int getStatus() {
    return exampleJNI.status_get();
  }

  public static String getPath() {
    return exampleJNI.path_get();
  }

  public static void print_vars() {
    exampleJNI.print_vars();
  }

  public static SWIGTYPE_p_int new_int(int value) {
    long cPtr = exampleJNI.new_int(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_Point new_Point(int x, int y) {
    long cPtr = exampleJNI.new_Point(x, y);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Point(cPtr, false);
  }

  public static String Point_print(SWIGTYPE_p_Point p) {
    return exampleJNI.Point_print(SWIGTYPE_p_Point.getCPtr(p));
  }

  public static void pt_print() {
    exampleJNI.pt_print();
  }

}
