/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface exampleConstants {
  public final static int ICONST = 42;
  public final static double FCONST = 2.1828;
  public final static char CCONST = 'x';
  public final static char CCONST2 = '\n';
  public final static String SCONST = "Hello World";
  public final static String SCONST2 = "\"Hello World\"";
  public final static double EXPR = 42+3*(2.1828);
  public final static int iconst = 37;
  public final static double fconst = 3.14;
}
