/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class cpp_moduleJNI {
  public final static native long new_MyClass(int jarg1);
  public final static native int MyClass_getValue(long jarg1, MyClass jarg1_);
  public final static native void MyClass_increment(long jarg1, MyClass jarg1_);
  public final static native void delete_MyClass(long jarg1);

    static {
        System.loadLibrary("cpp_java_swig");
    }

}
