/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Dmatrix extends java.util.AbstractList<SWIGTYPE_p_std__vectorT_double_t> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Dmatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Dmatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        matrixJNI.delete_Dmatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Dmatrix(SWIGTYPE_p_std__vectorT_double_t[] initialElements) {
    this();
    reserve(initialElements.length);

    for (SWIGTYPE_p_std__vectorT_double_t element : initialElements) {
      add(element);
    }
  }

  public Dmatrix(Iterable<SWIGTYPE_p_std__vectorT_double_t> initialElements) {
    this();
    for (SWIGTYPE_p_std__vectorT_double_t element : initialElements) {
      add(element);
    }
  }

  public SWIGTYPE_p_std__vectorT_double_t get(int index) {
    return doGet(index);
  }

  public SWIGTYPE_p_std__vectorT_double_t set(int index, SWIGTYPE_p_std__vectorT_double_t e) {
    return doSet(index, e);
  }

  public boolean add(SWIGTYPE_p_std__vectorT_double_t e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, SWIGTYPE_p_std__vectorT_double_t e) {
    modCount++;
    doAdd(index, e);
  }

  public SWIGTYPE_p_std__vectorT_double_t remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public Dmatrix() {
    this(matrixJNI.new_Dmatrix__SWIG_0(), true);
  }

  public Dmatrix(Dmatrix other) {
    this(matrixJNI.new_Dmatrix__SWIG_1(Dmatrix.getCPtr(other), other), true);
  }

  public long capacity() {
    return matrixJNI.Dmatrix_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    matrixJNI.Dmatrix_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return matrixJNI.Dmatrix_isEmpty(swigCPtr, this);
  }

  public void clear() {
    matrixJNI.Dmatrix_clear(swigCPtr, this);
  }

  public Dmatrix(int count, SWIGTYPE_p_std__vectorT_double_t value) {
    this(matrixJNI.new_Dmatrix__SWIG_2(count, SWIGTYPE_p_std__vectorT_double_t.getCPtr(value)), true);
  }

  private int doSize() {
    return matrixJNI.Dmatrix_doSize(swigCPtr, this);
  }

  private void doAdd(SWIGTYPE_p_std__vectorT_double_t x) {
    matrixJNI.Dmatrix_doAdd__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__vectorT_double_t.getCPtr(x));
  }

  private void doAdd(int index, SWIGTYPE_p_std__vectorT_double_t x) {
    matrixJNI.Dmatrix_doAdd__SWIG_1(swigCPtr, this, index, SWIGTYPE_p_std__vectorT_double_t.getCPtr(x));
  }

  private SWIGTYPE_p_std__vectorT_double_t doRemove(int index) {
    return new SWIGTYPE_p_std__vectorT_double_t(matrixJNI.Dmatrix_doRemove(swigCPtr, this, index), true);
  }

  private SWIGTYPE_p_std__vectorT_double_t doGet(int index) {
    return new SWIGTYPE_p_std__vectorT_double_t(matrixJNI.Dmatrix_doGet(swigCPtr, this, index), false);
  }

  private SWIGTYPE_p_std__vectorT_double_t doSet(int index, SWIGTYPE_p_std__vectorT_double_t val) {
    return new SWIGTYPE_p_std__vectorT_double_t(matrixJNI.Dmatrix_doSet(swigCPtr, this, index, SWIGTYPE_p_std__vectorT_double_t.getCPtr(val)), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    matrixJNI.Dmatrix_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
