/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class matrix {
  public static Dmatrix create() {
    return new Dmatrix(matrixJNI.create(), true);
  }

  public static void print_matrix(Dmatrix arg0) {
    matrixJNI.print_matrix(Dmatrix.getCPtr(arg0), arg0);
  }

}
