/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class saJNI {
  public final static native void addr_houseno_set(long jarg1, addr jarg1_, int jarg2);
  public final static native int addr_houseno_get(long jarg1, addr jarg1_);
  public final static native void addr_street_set(long jarg1, addr jarg1_, String jarg2);
  public final static native String addr_street_get(long jarg1, addr jarg1_);
  public final static native void addr_city_set(long jarg1, addr jarg1_, String jarg2);
  public final static native String addr_city_get(long jarg1, addr jarg1_);
  public final static native void addr_state_set(long jarg1, addr jarg1_, String jarg2);
  public final static native String addr_state_get(long jarg1, addr jarg1_);
  public final static native long new_addr();
  public final static native void delete_addr(long jarg1);
  public final static native void emp_empno_set(long jarg1, emp jarg1_, int jarg2);
  public final static native int emp_empno_get(long jarg1, emp jarg1_);
  public final static native void emp_name_set(long jarg1, emp jarg1_, String jarg2);
  public final static native String emp_name_get(long jarg1, emp jarg1_);
  public final static native void emp_desig_set(long jarg1, emp jarg1_, String jarg2);
  public final static native String emp_desig_get(long jarg1, emp jarg1_);
  public final static native void emp_address_set(long jarg1, emp jarg1_, long jarg2, addr jarg2_);
  public final static native long emp_address_get(long jarg1, emp jarg1_);
  public final static native void emp_basic_set(long jarg1, emp jarg1_, float jarg2);
  public final static native float emp_basic_get(long jarg1, emp jarg1_);
  public final static native long new_emp();
  public final static native void delete_emp(long jarg1);
  public final static native void worker_set(long jarg1, emp jarg1_);
  public final static native long worker_get();
}
