/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static void f1(String s) {
    exampleJNI.f1(s);
  }

  public static void f2(byte[] BYTE) {
    exampleJNI.f2(BYTE);
  }

  public static void f3(StringBuffer SBUF) {
    exampleJNI.f3(SBUF);
  }

}
