/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static Vector addv(Vector a, Vector b) {
    return new Vector(exampleJNI.addv(Vector.getCPtr(a), a, Vector.getCPtr(b), b), true);
  }

}
