/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector(double x, double y, double z) {
    this(exampleJNI.new_Vector(x, y, z), true);
  }

  public String print() {
    return exampleJNI.Vector_print(swigCPtr, this);
  }

}
