/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class VectorArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_VectorArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorArray(int maxsize) {
    this(exampleJNI.new_VectorArray(maxsize), true);
  }

  public int size() {
    return exampleJNI.VectorArray_size(swigCPtr, this);
  }

  public Vector get(int index) {
    return new Vector(exampleJNI.VectorArray_get(swigCPtr, this, index), false);
  }

  public void set(int index, Vector a) {
    exampleJNI.VectorArray_set(swigCPtr, this, index, Vector.getCPtr(a), a);
  }

}
