/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SquareC {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SquareC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SquareC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        squareJNI.delete_SquareC(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SquareC(double x, double y) {
    this(squareJNI.new_SquareC(x, y), true);
  }

  public double area() {
    return squareJNI.SquareC_area(swigCPtr, this);
  }

}
