/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class squareJNI {
  public final static native long new_SquareC(double jarg1, double jarg2);
  public final static native double SquareC_area(long jarg1, SquareC jarg1_);
  public final static native void delete_SquareC(long jarg1);
}
