/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static void add(SWIGTYPE_p_int x, SWIGTYPE_p_int y, SWIGTYPE_p_int result) {
    exampleJNI.add(SWIGTYPE_p_int.getCPtr(x), SWIGTYPE_p_int.getCPtr(y), SWIGTYPE_p_int.getCPtr(result));
  }

  public static SWIGTYPE_p_int new_intp() {
    long cPtr = exampleJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = exampleJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    exampleJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    exampleJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return exampleJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void sub(int arg0, int arg1, int[] OUTPUT) {
    exampleJNI.sub(arg0, arg1, OUTPUT);
  }

  public static int divide(int n, int d, int[] r) {
    return exampleJNI.divide(n, d, r);
  }

}
