/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class calloc_swig {
  public static void allocation_show() {
    calloc_swigJNI.allocation_show();
  }

  public static SWIGTYPE_p_double new_SWIGArrayUtility(int nelements) {
    long cPtr = calloc_swigJNI.new_SWIGArrayUtility(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_SWIGArrayUtility(SWIGTYPE_p_double ary) {
    calloc_swigJNI.delete_SWIGArrayUtility(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double SWIGArrayUtility_getitem(SWIGTYPE_p_double ary, int index) {
    return calloc_swigJNI.SWIGArrayUtility_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void SWIGArrayUtility_setitem(SWIGTYPE_p_double ary, int index, double value) {
    calloc_swigJNI.SWIGArrayUtility_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

}
