/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class calloc_swigJNI {
  public final static native void struct1_T_dyn_arr_set(long jarg1, struct1_T jarg1_, long jarg2);
  public final static native long struct1_T_dyn_arr_get(long jarg1, struct1_T jarg1_);
  public final static native long new_struct1_T();
  public final static native void delete_struct1_T(long jarg1);
  public final static native void allocation_show();
  public final static native long new_SWIGArrayUtility(int jarg1);
  public final static native void delete_SWIGArrayUtility(long jarg1);
  public final static native double SWIGArrayUtility_getitem(long jarg1, int jarg2);
  public final static native void SWIGArrayUtility_setitem(long jarg1, int jarg2, double jarg3);
}
