/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class struct1_T {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected struct1_T(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(struct1_T obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        calloc_swigJNI.delete_struct1_T(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDyn_arr(SWIGTYPE_p_double value) {
    calloc_swigJNI.struct1_T_dyn_arr_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getDyn_arr() {
    long cPtr = calloc_swigJNI.struct1_T_dyn_arr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public struct1_T() {
    this(calloc_swigJNI.new_struct1_T(), true);
  }

}
