/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native long new_Foo();
  public final static native void Foo_enum_test(long jarg1, Foo jarg1_, int jarg2);
  public final static native void delete_Foo(long jarg1);
  public final static native void enum_test(int jarg1, int jarg2);
}
