/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Foo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Foo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Foo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Foo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Foo() {
    this(exampleJNI.new_Foo(), true);
  }

  public void enum_test(Foo.speed s) {
    exampleJNI.Foo_enum_test(swigCPtr, this, s.swigValue());
  }

  public final static class speed {
    public final static Foo.speed IMPULSE = new Foo.speed("IMPULSE", 10);
    public final static Foo.speed WARP = new Foo.speed("WARP", 20);
    public final static Foo.speed LUDICROUS = new Foo.speed("LUDICROUS", 30);

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static speed swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + speed.class + " with value " + swigValue);
    }

    private speed(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private speed(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private speed(String swigName, speed swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static speed[] swigValues = { IMPULSE, WARP, LUDICROUS };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
