/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class PersonC {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PersonC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PersonC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        personJNI.delete_PersonC(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PersonC(String arg0, int arg1) {
    this(personJNI.new_PersonC(arg0, arg1), true);
  }

  public String get_name() {
    return personJNI.PersonC_get_name(swigCPtr, this);
  }

  public void set_name(SWIGTYPE_p_std__string arg0) {
    personJNI.PersonC_set_name(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(arg0));
  }

  public int get_age() {
    return personJNI.PersonC_get_age(swigCPtr, this);
  }

  public void set_age(int arg0) {
    personJNI.PersonC_set_age(swigCPtr, this, arg0);
  }

}
