/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class personJNI {
  public final static native long new_PersonC(String jarg1, int jarg2);
  public final static native String PersonC_get_name(long jarg1, PersonC jarg1_);
  public final static native void PersonC_set_name(long jarg1, PersonC jarg1_, long jarg2);
  public final static native int PersonC_get_age(long jarg1, PersonC jarg1_);
  public final static native void PersonC_set_age(long jarg1, PersonC jarg1_, int jarg2);
  public final static native void delete_PersonC(long jarg1);
}
