/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniDemo */

#ifndef _Included_JniDemo
#define _Included_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniDemo
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JniDemo_set
  (JNIEnv *, jclass, jint);

/*
 * Class:     JniDemo
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JniDemo_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
