/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class EmployeeList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected EmployeeList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(EmployeeList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_EmployeeList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public EmployeeList() {
    this(exampleJNI.new_EmployeeList(), true);
  }

  public void addEmployee(Employee p) {
    exampleJNI.EmployeeList_addEmployee(swigCPtr, this, Employee.getCPtr(p), p);
  }

  public Employee get_item(int i) {
    long cPtr = exampleJNI.EmployeeList_get_item(swigCPtr, this, i);
    return (cPtr == 0) ? null : new Employee(cPtr, false);
  }

}
