/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Employee {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Employee(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Employee obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Employee(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    exampleJNI.Employee_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    exampleJNI.Employee_change_ownership(this, swigCPtr, true);
  }

  public Employee(String n) {
    this(exampleJNI.new_Employee(n), true);
    exampleJNI.Employee_director_connect(this, swigCPtr, true, true);
  }

  public String getTitle() {
    return (getClass() == Employee.class) ? exampleJNI.Employee_getTitle(swigCPtr, this) : exampleJNI.Employee_getTitleSwigExplicitEmployee(swigCPtr, this);
  }

  public String getName() {
    return (getClass() == Employee.class) ? exampleJNI.Employee_getName(swigCPtr, this) : exampleJNI.Employee_getNameSwigExplicitEmployee(swigCPtr, this);
  }

  public String getPosition() {
    return (getClass() == Employee.class) ? exampleJNI.Employee_getPosition(swigCPtr, this) : exampleJNI.Employee_getPositionSwigExplicitEmployee(swigCPtr, this);
  }

}
