/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_example_WRAP_H_
#define SWIG_example_WRAP_H_

class SwigDirector_Employee : public Employee, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Employee(JNIEnv *jenv, char const *n);
    virtual std::string getTitle();
    virtual std::string getName();
    virtual std::string getPosition() const;
    virtual ~SwigDirector_Employee();
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<3> swig_override;
};

class SwigDirector_Manager : public Manager, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Manager(JNIEnv *jenv, char const *n);
    virtual std::string getTitle();
    virtual std::string getName();
    virtual std::string getPosition() const;
    virtual ~SwigDirector_Manager();
public:
    bool swig_overrides(int n) {
      return (n < 3 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<3> swig_override;
};


#endif
