/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class Manager extends Employee {
  private transient long swigCPtr;

  protected Manager(long cPtr, boolean cMemoryOwn) {
    super(exampleJNI.Manager_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Manager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        exampleJNI.delete_Manager(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    exampleJNI.Manager_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    exampleJNI.Manager_change_ownership(this, swigCPtr, true);
  }

  public Manager(String n) {
    this(exampleJNI.new_Manager(n), true);
    exampleJNI.Manager_director_connect(this, swigCPtr, true, true);
  }

  public String getPosition() {
    return (getClass() == Manager.class) ? exampleJNI.Manager_getPosition(swigCPtr, this) : exampleJNI.Manager_getPositionSwigExplicitManager(swigCPtr, this);
  }

}
