/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class struct_in_pointerJNI {
  public final static native void d_data_x1_set(long jarg1, d_data jarg1_, int jarg2);
  public final static native int d_data_x1_get(long jarg1, d_data jarg1_);
  public final static native void d_data_pint_set(long jarg1, d_data jarg1_, long jarg2);
  public final static native long d_data_pint_get(long jarg1, d_data jarg1_);
  public final static native void d_data_pdoub_set(long jarg1, d_data jarg1_, long jarg2);
  public final static native long d_data_pdoub_get(long jarg1, d_data jarg1_);
  public final static native long new_d_data();
  public final static native void delete_d_data(long jarg1);
  public final static native void demoStruct_set(long jarg1, d_data jarg1_);
  public final static native long demoStruct_get();
  public final static native long new_intp();
  public final static native long copy_intp(int jarg1);
  public final static native void delete_intp(long jarg1);
  public final static native void intp_assign(long jarg1, int jarg2);
  public final static native int intp_value(long jarg1);
  public final static native long new_doublep();
  public final static native long copy_doublep(double jarg1);
  public final static native void delete_doublep(long jarg1);
  public final static native void doublep_assign(long jarg1, double jarg2);
  public final static native double doublep_value(long jarg1);
}
