/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ls_swig {
  public static void argInit_double_arr(double[] arr) {
    ls_swigJNI.argInit_double_arr(arr);
  }

  public static int argInit_double(int val) {
    return ls_swigJNI.argInit_double(val);
  }

  public static SWIGTYPE_p_double new_double_1d_array(int nelements) {
    long cPtr = ls_swigJNI.new_double_1d_array(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_double_1d_array(SWIGTYPE_p_double ary) {
    ls_swigJNI.delete_double_1d_array(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double double_1d_array_getitem(SWIGTYPE_p_double ary, int index) {
    return ls_swigJNI.double_1d_array_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void double_1d_array_setitem(SWIGTYPE_p_double ary, int index, double value) {
    ls_swigJNI.double_1d_array_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }

}
