/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ls_swigJNI {
  public final static native void argInit_double_arr(double[] jarg1);
  public final static native int argInit_double(int jarg1);
  public final static native long new_double_1d_array(int jarg1);
  public final static native void delete_double_1d_array(long jarg1);
  public final static native double double_1d_array_getitem(long jarg1, int jarg2);
  public final static native void double_1d_array_setitem(long jarg1, int jarg2, double jarg3);
}
