/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native long point_create(int jarg1, int jarg2);
  public final static native String point_toString1(long jarg1);
  public final static native void free(long jarg1);
  public final static native String point_toString2(long jarg1);
}
