/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class doubleArrayJNI {
  public final static native int numFoo();
  public final static native long getDoubleArray();
  public final static native long new_SWIGArrayUtility(int jarg1);
  public final static native void delete_SWIGArrayUtility(long jarg1);
  public final static native double SWIGArrayUtility_getitem(long jarg1, int jarg2);
  public final static native void SWIGArrayUtility_setitem(long jarg1, int jarg2, double jarg3);
}
