/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class doubleArray {
  public static int numFoo() {
    return doubleArrayJNI.numFoo();
  }

  public static SWIGTYPE_p_double getDoubleArray() {
    long cPtr = doubleArrayJNI.getDoubleArray();
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_double new_SWIGArrayUtility(int nelements) {
    long cPtr = doubleArrayJNI.new_SWIGArrayUtility(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public static void delete_SWIGArrayUtility(SWIGTYPE_p_double ary) {
    doubleArrayJNI.delete_SWIGArrayUtility(SWIGTYPE_p_double.getCPtr(ary));
  }

  public static double SWIGArrayUtility_getitem(SWIGTYPE_p_double ary, int index) {
    return doubleArrayJNI.SWIGArrayUtility_getitem(SWIGTYPE_p_double.getCPtr(ary), index);
  }

  public static void SWIGArrayUtility_setitem(SWIGTYPE_p_double ary, int index, double value) {
    doubleArrayJNI.SWIGArrayUtility_setitem(SWIGTYPE_p_double.getCPtr(ary), index, value);
  }


  public static double[] getDoubleArrayImpl() {
    final int num = numFoo();
    double ret[] = new double[num];
    SWIGTYPE_p_double result = getDoubleArray();
    for (int i = 0; i < num; ++i) {
        ret[i] = SWIGArrayUtility_getitem(result, i);
    }
    return ret;
  } 

}
