/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class testJNI {
  public final static native long new_foo_array(int jarg1);
  public final static native void delete_foo_array(long jarg1, Foo jarg1_);
  public final static native long foo_array_getitem(long jarg1, Foo jarg1_, int jarg2);
  public final static native void foo_array_setitem(long jarg1, Foo jarg1_, int jarg2, long jarg3, Foo jarg3_);
  public final static native void Foo_v_set(long jarg1, Foo jarg1_, int jarg2);
  public final static native int Foo_v_get(long jarg1, Foo jarg1_);
  public final static native long new_Foo();
  public final static native void delete_Foo(long jarg1);
  public final static native long getFooImpl();
  public final static native int numFoo();
}
