/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class example {
  public static void setPtptr(SWIGTYPE_p_Point value) {
    exampleJNI.ptptr_set(SWIGTYPE_p_Point.getCPtr(value));
  }

  public static SWIGTYPE_p_Point getPtptr() {
    long cPtr = exampleJNI.ptptr_get();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Point(cPtr, false);
  }

  public static void setPt(SWIGTYPE_p_Point value) {
    exampleJNI.pt_set(SWIGTYPE_p_Point.getCPtr(value));
  }

  public static SWIGTYPE_p_Point getPt() {
    return new SWIGTYPE_p_Point(exampleJNI.pt_get(), true);
  }

  public static String getPath() {
    return exampleJNI.path_get();
  }

  public static SWIGTYPE_p_Point new_Point(int x, int y) {
    long cPtr = exampleJNI.new_Point(x, y);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Point(cPtr, false);
  }

  public static String Point_print(SWIGTYPE_p_Point p) {
    return exampleJNI.Point_print(SWIGTYPE_p_Point.getCPtr(p));
  }

  public static void pt_print() {
    exampleJNI.pt_print();
  }

}
