/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class exampleJNI {
  public final static native void ptptr_set(long jarg1);
  public final static native long ptptr_get();
  public final static native void pt_set(long jarg1);
  public final static native long pt_get();
  public final static native String path_get();
  public final static native long new_Point(int jarg1, int jarg2);
  public final static native String Point_print(long jarg1);
  public final static native void pt_print();
}
