/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class sa {
  public static void setDemoStruct(demo_data value) {
    saJNI.demoStruct_set(demo_data.getCPtr(value), value);
  }

  public static demo_data getDemoStruct() {
    long cPtr = saJNI.demoStruct_get();
    return (cPtr == 0) ? null : new demo_data(cPtr, false);
  }

  public static SWIGTYPE_p_int new_intArray(int nelements) {
    long cPtr = saJNI.new_intArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intArray(SWIGTYPE_p_int ary) {
    saJNI.delete_intArray(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int intArray_getitem(SWIGTYPE_p_int ary, int index) {
    return saJNI.intArray_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void intArray_setitem(SWIGTYPE_p_int ary, int index, int value) {
    saJNI.intArray_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_a_16__char new_char4_16() {
    long cPtr = saJNI.new_char4_16();
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_16__char(cPtr, false);
  }

  public static void free_char4_16(SWIGTYPE_p_a_16__char x) {
    saJNI.free_char4_16(SWIGTYPE_p_a_16__char.getCPtr(x));
  }

  public static void char4_16_set(SWIGTYPE_p_a_16__char x, int i, int j, char v) {
    saJNI.char4_16_set(SWIGTYPE_p_a_16__char.getCPtr(x), i, j, v);
  }

  public static char char4_16_get(SWIGTYPE_p_a_16__char x, int i, int j) {
    return saJNI.char4_16_get(SWIGTYPE_p_a_16__char.getCPtr(x), i, j);
  }

}
