/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class saJNI {
  public final static native void demo_data_x1_set(long jarg1, demo_data jarg1_, int jarg2);
  public final static native int demo_data_x1_get(long jarg1, demo_data jarg1_);
  public final static native void demo_data_s1_set(long jarg1, demo_data jarg1_, long jarg2);
  public final static native long demo_data_s1_get(long jarg1, demo_data jarg1_);
  public final static native void demo_data_s2_set(long jarg1, demo_data jarg1_, long jarg2);
  public final static native long demo_data_s2_get(long jarg1, demo_data jarg1_);
  public final static native void demo_data_s3_set(long jarg1, demo_data jarg1_, long jarg2);
  public final static native long demo_data_s3_get(long jarg1, demo_data jarg1_);
  public final static native void demo_data_x2_set(long jarg1, demo_data jarg1_, long jarg2);
  public final static native long demo_data_x2_get(long jarg1, demo_data jarg1_);
  public final static native long new_demo_data();
  public final static native void delete_demo_data(long jarg1);
  public final static native void demoStruct_set(long jarg1, demo_data jarg1_);
  public final static native long demoStruct_get();
  public final static native long new_intArray(int jarg1);
  public final static native void delete_intArray(long jarg1);
  public final static native int intArray_getitem(long jarg1, int jarg2);
  public final static native void intArray_setitem(long jarg1, int jarg2, int jarg3);
  public final static native long new_char4_16();
  public final static native void free_char4_16(long jarg1);
  public final static native void char4_16_set(long jarg1, int jarg2, int jarg3, char jarg4);
  public final static native char char4_16_get(long jarg1, int jarg2, int jarg3);
}
