/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class module_struct_access_3 {
  public static void setDStruct(D_data value) {
    module_struct_access_3JNI.dStruct_set(D_data.getCPtr(value), value);
  }

  public static D_data getDStruct() {
    long cPtr = module_struct_access_3JNI.dStruct_get();
    return (cPtr == 0) ? null : new D_data(cPtr, false);
  }

  public static SWIGTYPE_p_int new_intArray(int nelements) {
    long cPtr = module_struct_access_3JNI.new_intArray(nelements);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intArray(SWIGTYPE_p_int ary) {
    module_struct_access_3JNI.delete_intArray(SWIGTYPE_p_int.getCPtr(ary));
  }

  public static int intArray_getitem(SWIGTYPE_p_int ary, int index) {
    return module_struct_access_3JNI.intArray_getitem(SWIGTYPE_p_int.getCPtr(ary), index);
  }

  public static void intArray_setitem(SWIGTYPE_p_int ary, int index, int value) {
    module_struct_access_3JNI.intArray_setitem(SWIGTYPE_p_int.getCPtr(ary), index, value);
  }

  public static SWIGTYPE_p_a_4__a_5__int int_array_3_4_5(int size) {
    long cPtr = module_struct_access_3JNI.int_array_3_4_5(size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_4__a_5__int(cPtr, false);
  }

  public static void int_3_4_5_set(SWIGTYPE_p_a_4__a_5__int x, int i, int j, int k, int v) {
    module_struct_access_3JNI.int_3_4_5_set(SWIGTYPE_p_a_4__a_5__int.getCPtr(x), i, j, k, v);
  }

  public static int int_3_4_5_get(SWIGTYPE_p_a_4__a_5__int x, int i, int j, int k) {
    return module_struct_access_3JNI.int_3_4_5_get(SWIGTYPE_p_a_4__a_5__int.getCPtr(x), i, j, k);
  }

}
