/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class module_struct_access_3JNI {
  public final static native void D_data_x1_set(long jarg1, D_data jarg1_, int jarg2);
  public final static native int D_data_x1_get(long jarg1, D_data jarg1_);
  public final static native void D_data_a1_set(long jarg1, D_data jarg1_, long jarg2);
  public final static native long D_data_a1_get(long jarg1, D_data jarg1_);
  public final static native long new_D_data();
  public final static native void delete_D_data(long jarg1);
  public final static native void dStruct_set(long jarg1, D_data jarg1_);
  public final static native long dStruct_get();
  public final static native long new_intArray(int jarg1);
  public final static native void delete_intArray(long jarg1);
  public final static native int intArray_getitem(long jarg1, int jarg2);
  public final static native void intArray_setitem(long jarg1, int jarg2, int jarg3);
  public final static native long int_array_3_4_5(int jarg1);
  public final static native void int_3_4_5_set(long jarg1, int jarg2, int jarg3, int jarg4, int jarg5);
  public final static native int int_3_4_5_get(long jarg1, int jarg2, int jarg3, int jarg4);
}
